CREATE ROLE app LOGIN NOINHERIT;

GRANT CONNECT 
ON DATABASE postgres 
TO app;

GRANT USAGE 
ON SCHEMA public 
TO app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES 
IN SCHEMA public
TO app;

GRANT USAGE, SELECT 
ON ALL SEQUENCES 
IN SCHEMA public 
TO app;

ALTER DEFAULT PRIVILEGES
FOR ROLE flyway
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES
TO app;

ALTER DEFAULT PRIVILEGES
FOR ROLE flyway
IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES
TO app;